# Colors - Original casing (will be parameterized to lowercase)
title: "Colors"
description: "Hex color codes that can be shared, cross-platform. They can be converted at point of usage, such as HSL for web or CMYK for print."
items:
  Dark: "#030303"
  Light: "#ffffff"
  Primary: "#02394A"
