# Spacing - Original casing (will be parameterized)
title: "Spacing"
description: "Consistent spacing sizes, based on a ratio, with min and max sizes. This allows you to set spacing based on the context size."
meta:
  scaleGenerator: "https://utopia.fyi/space/calculator/?c=330,18,1.2,1200,24,1.25,6,2,&s=0.75|0.5|0.25,1.5|2|3|4|6|8,s-l|s-xl&g=s,l,xl,12"
items:
  Zero: { min: 0, max: 1 }
  3XS: { min: 5, max: 6 }
  2XS: { min: 9, max: 12 }
  XS: { min: 14, max: 18 }
  S: { min: 18, max: 24 }
  M: { min: 27, max: 36 }
  L: { min: 36, max: 48 }
  XL: { min: 54, max: 72 }
  2XL: { min: 72, max: 96 }
  3XL: { min: 108, max: 144 }
  4XL: { min: 144, max: 192 }
  # Compound spacing - with spaces and dashes (will become s-m, m-l, etc.)
  "3XS - 2XS": { min: 5, max: 12 }
  "2XS - XS": { min: 9, max: 18 }
  "XS - S": { min: 14, max: 24 }
  "S - M": { min: 18, max: 36 }
  "M - L": { min: 27, max: 48 }
  "L - XL": { min: 36, max: 72 }
  "XL - 2XL": { min: 54, max: 96 }
  "2XL - 3XL": { min: 72, max: 144 }
  "3XL - 4XL": { min: 108, max: 192 }
  "S - L": { min: 18, max: 48 }
  "S - XL": { min: 18, max: 72 }
