# Text sizes - with "Step" prefix
title: "Text Sizes"
description: "A minimum and maximum text size allows you to pick the right size from a ratio, depending on the context size."
meta:
  scaleGenerator: "https://utopia.fyi/type/calculator/?c=330,18,1.175,1200,24,1.25,7,1,&s=0.75%7C0.5%7C0.25,1.5%7C2%7C3%7C4%7C6,s-l&g=s,l,xl,12"
items:
  "Step 00": { min: 15, max: 16 }
  "Step 0": { min: 18, max: 20 }
  "Step 1": { min: 21.6, max: 25 }
  "Step 2": { min: 25.92, max: 31.25 }
  "Step 3": { min: 31.1, max: 39.06 }
  "Step 4": { min: 39.06, max: 48.83 }
  "Step 5": { min: 44.79, max: 61.04 }
